import type { LegalCase } from '../../src/types';

export const INITIAL_CASES: LegalCase[] = [
  {
    id: 'case-101',
    caseNumber: 'PL-2026-8842',
    clientName: 'Ahmet Yılmaz',
    clientEmail: 'ahmet.yilmaz@gmail.com',
    clientPhone: '+48 570 123 456',
    caseType: 'Geçici Oturma İzni (Karta Pobytu)',
    caseCategory: 'oturtma',
    city: 'Varşova (Mazowieckie)',
    status: 'pending_docs',
    urgency: 'critical',
    createdAt: '2026-07-15',
    updatedAt: '2026-07-28',
    assignedLawyer: 'Av. Piotr Kowalski',
    lawyerAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    progressPercent: 60,
    documents: [
      {
        id: 'doc-1',
        name: 'Wniosek_Oturma_Izni_Signed.pdf',
        size: '2.4 MB',
        type: 'pdf',
        uploadedAt: '2026-07-16',
        status: 'approved',
      },
      {
        id: 'doc-2',
        name: 'Is_Sozlesmesi_Umowa_o_prace.pdf',
        size: '1.8 MB',
        type: 'pdf',
        uploadedAt: '2026-07-16',
        status: 'approved',
      },
      {
        id: 'doc-3',
        name: 'ZUS_RCA_Sigorta_Beyani_2026.pdf',
        size: '850 KB',
        type: 'pdf',
        uploadedAt: '2026-07-25',
        status: 'pending',
      },
      {
        id: 'doc-4',
        name: 'Ev_Kira_Kontrati_Warszawa.pdf',
        size: '3.1 MB',
        type: 'pdf',
        uploadedAt: '2026-07-27',
        status: 'rejected',
        rejectionReason: 'Ev sahibinin noter onaylı imzası eksik veya süresi dolmuş. Lütfen güncel Zgłoszenie zameldowania ekleyin.',
      },
    ],
    timeline: [
      {
        id: 't-1',
        title: 'Başvuru ve Ön Değerlendirme Alındı',
        description: 'Sistem üzerinden form iletildi, belgeler tasnif edildi.',
        date: '15 Temmuz 2026',
        status: 'completed',
        actor: 'Müşteri',
      },
      {
        id: 't-2',
        title: 'Sorumlu Avukata Atandı',
        description: 'Dosyanız Varşova Yabancılar Dairesi uzmanı Av. Piotr Kowalski tarafına atandı.',
        date: '16 Temmuz 2026',
        status: 'completed',
        actor: 'Hukuk Bürosu',
      },
      {
        id: 't-3',
        title: 'Hukuki İnceleme Yapıldı',
        description: 'İş sözleşmesi ve ZUS belgeleri Polonya mevzuatına uygun bulundu.',
        date: '20 Temmuz 2026',
        status: 'completed',
        actor: 'Av. Piotr Kowalski',
      },
      {
        id: 't-4',
        title: 'Ek Belge Bekleniyor (Noter Onaylı Kira Kontratı)',
        description: 'Urząd Mazowiecki eksik evrak çağrısı öncesi dosyanızı tamamlamamız gerekiyor.',
        date: '28 Temmuz 2026',
        status: 'current',
        actor: 'Sistem Uyarısı',
      },
      {
        id: 't-5',
        title: 'Urząd Mazowiecki’ye Resmi Teslimat',
        description: 'Dosya randevu günü doğrudan dairesine sunulacak.',
        status: 'upcoming',
      },
      {
        id: 't-6',
        title: 'Karar (Decyzja) ve Kart Basımı',
        description: 'Oturum kararının tebliği ve biyo-kart teslimi.',
        status: 'upcoming',
      },
    ],
    internalNotes: [
      {
        id: 'note-1',
        author: 'Av. Piotr Kowalski',
        date: '2026-07-20 14:30',
        content: 'Müşterinin maaşı Mazowiecki valiliği asgari gelir kriterinin (3400 PLN net) üzerinde. İşveren firmasının NIP ve KRS kaydı temiz.',
      },
      {
        id: 'note-2',
        author: 'Av. Zeynep Yılmaz',
        date: '2026-07-27 10:15',
        content: 'Kira kontratı süresi 3 ay sonra bitiyor. Valilik red verebilir, ev sahibinden ek süre uzatımı istenmeli.',
      },
    ],
    messages: [
      {
        id: 'msg-1',
        senderId: 'lawyer-1',
        senderName: 'Av. Piotr Kowalski',
        senderRole: 'lawyer',
        avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
        text: 'Merhaba Ahmet Bey, Karta Pobytu başvurunuz için hazırladığımız dilekçe taslağı hazır. Kira kontratındaki güncellemeyi bekliyoruz.',
        timestamp: '27 Temmuz 2026 - 11:20',
      },
      {
        id: 'msg-2',
        senderId: 'client-1',
        senderName: 'Ahmet Yılmaz',
        senderRole: 'client',
        text: 'Piotr Bey merhaba, ev sahibimle görüştüm. Yeni kontratı noter onaylı olarak yarın sabah yükleyeceğim.',
        timestamp: '27 Temmuz 2026 - 14:45',
      },
      {
        id: 'msg-3',
        senderId: 'lawyer-1',
        senderName: 'Av. Piotr Kowalski',
        senderRole: 'lawyer',
        avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
        text: 'Harika! Yükler yüklemez kontrol edip randevunuzu kesinleştireceğiz. Acil durum kodunuz sisteme işlendi.',
        timestamp: '27 Temmuz 2026 - 15:02',
      },
    ],
    formSummary: {
      'Polonya Şehri': 'Varşova / Warszawa',
      'Mevcut Statü': 'Çalışma İzni (Zezwolenie typ A)',
      'Polonya Giriş Tarihi': '12 Mart 2024',
      'İşveren Unvanı': 'TechPoland Sp. z o.o.',
      'Aylık Brüt Gelir': '9.800 PLN',
      'Aciliyet Notu': 'Eski kartın süresi 20 gün sonra bitiyor (Çok Acil)',
    },
  },
  {
    id: 'case-102',
    caseNumber: 'PL-2026-9210',
    clientName: 'Elif Kaya Demir',
    clientEmail: 'elif.kaya@outlook.com',
    clientPhone: '+48 692 887 112',
    caseType: 'Spółka z o.o. (Limited Şirket) Kuruluşu',
    caseCategory: 'sirket',
    city: 'Kraków (Małopolskie)',
    status: 'in_review',
    urgency: 'urgent',
    createdAt: '2026-07-20',
    updatedAt: '2026-07-28',
    assignedLawyer: 'Av. Zeynep Yılmaz Kowalska',
    lawyerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    progressPercent: 45,
    documents: [
      {
        id: 'doc-10',
        name: 'Pasaport_Taramasi_ElifKaya.pdf',
        size: '4.1 MB',
        type: 'pdf',
        uploadedAt: '2026-07-21',
        status: 'approved',
      },
      {
        id: 'doc-11',
        name: 'S24_Sirket_Ana_Sozlesmesi_Draft.pdf',
        size: '1.2 MB',
        type: 'pdf',
        uploadedAt: '2026-07-22',
        status: 'approved',
      },
    ],
    timeline: [
      {
        id: 't-10',
        title: 'Şirket Başvuru Formu Alındı',
        description: 'S24 portalı üzerinden ön hazırlıklar tamamlandı.',
        date: '20 Temmuz 2026',
        status: 'completed',
      },
      {
        id: 't-11',
        title: 'PKD (Faaliyet Kodları) İncelemesi',
        description: 'Yazılım ve e-ticaret alanları PKD kodları eklendi.',
        date: '24 Temmuz 2026',
        status: 'completed',
      },
      {
        id: 't-12',
        title: 'Avukat İncelemesi ve KRS Hazırlığı',
        description: 'Kraków Ticaret Mahkemesi başvuru evrakları hazırlanıyor.',
        date: '28 Temmuz 2026',
        status: 'current',
      },
    ],
    internalNotes: [
      {
        id: 'note-10',
        author: 'Av. Zeynep Yılmaz',
        date: '2026-07-22 16:00',
        content: 'Müşteri PESEL numarası almak istiyor. ePUAP profili açılması için talimat verildi.',
      },
    ],
    messages: [
      {
        id: 'msg-10',
        senderId: 'lawyer-2',
        senderName: 'Av. Zeynep Yılmaz Kowalska',
        senderRole: 'lawyer',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
        text: 'Elif Hanım merhaba, şirket ana sözleşmeniz S24 sistemine yüklendi. İmza için ePUAP şifrenizi hazırlayabilirsiniz.',
        timestamp: '28 Temmuz 2026 - 09:15',
      },
    ],
    formSummary: {
      'Şirket Unvanı': 'NordicTech Poland Sp. z o.o.',
      'Sermaye': '5.000 PLN',
      'Şehir': 'Kraków',
      'Ortak Sayısı': '2 (Türk Vatandaşı)',
      'PESEL Durumu': 'Mevcut değil (Vekaletname ile alınacak)',
    },
  },
  {
    id: 'case-103',
    caseNumber: 'PL-2026-7731',
    clientName: 'Mehmet Ali Şahin',
    clientEmail: 'm.sahin@polandconsult.com',
    clientPhone: '+48 511 990 334',
    caseType: 'Aile Birleşimi (Połączenie Rodziny)',
    caseCategory: 'aile',
    city: 'Wrocław (Dolnośląskie)',
    status: 'submitted',
    urgency: 'normal',
    createdAt: '2026-06-10',
    updatedAt: '2026-07-20',
    assignedLawyer: 'Av. Marek Nowak',
    lawyerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    progressPercent: 80,
    documents: [
      {
        id: 'doc-20',
        name: 'Evlilik_Cuzdani_Apostil.pdf',
        size: '5.2 MB',
        type: 'pdf',
        uploadedAt: '2026-06-12',
        status: 'approved',
      },
    ],
    timeline: [
      {
        id: 't-20',
        title: 'Evraklar Valiliğe Verildi',
        description: 'Dolnośląski Urząd Wojewódzki dosya kaydı açıldı.',
        date: '15 Haziran 2026',
        status: 'completed',
      },
      {
        id: 't-21',
        title: 'Karar (Decyzja) Aşamasında',
        description: 'Valilik incelemesi devam ediyor.',
        date: '20 Temmuz 2026',
        status: 'current',
      },
    ],
    internalNotes: [],
    messages: [],
    formSummary: {
      'Eşin Durumu': 'Mavi Kart (Niebieska Karta EU) Sahibi',
      'Çocuk Sayısı': '1',
      'Şehir': 'Wrocław',
    },
  },
  {
    id: 'case-104',
    caseNumber: 'PL-2026-9912',
    clientName: 'Canan Arslan',
    clientEmail: 'canan.arslan@gmail.com',
    clientPhone: '+48 789 443 112',
    caseType: 'Polonya Vatandaşlığı Başvurusu',
    caseCategory: 'vatandasilik',
    city: 'Poznań (Wielkopolskie)',
    status: 'assigned',
    urgency: 'normal',
    createdAt: '2026-07-26',
    updatedAt: '2026-07-27',
    assignedLawyer: 'Av. Piotr Kowalski',
    lawyerAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    progressPercent: 20,
    documents: [],
    timeline: [
      {
        id: 't-30',
        title: 'Ön Kayıt Tamamlandı',
        description: 'Vatandaşlık şartları ön kontrol edildi (B1 Lehçe belgesi mevcut).',
        date: '26 Temmuz 2026',
        status: 'completed',
      },
    ],
    internalNotes: [],
    messages: [],
    formSummary: {
      'Polonya İkamet Süresi': '5 Yıl Kesintisiz (Karta Stałego Pobytu)',
      'Lehçe Sertifikası': 'B1 Państwowy Egzamin (Mevcut)',
    },
  },
];
